[metadata]
name = programver
version = 2.0.0

[options]
packages = find:
include_package_data = True

[options.packages.find]
include =
    programver
    programver.*

[options.package_data]
programver.imgs =
    *.gif
    *.png

[options.entry_points]
console_scripts =
    programver = programver.__main__:main
